In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

In [2]:
import os

In [3]:
from google.colab import drive, files
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
%cd '/content/drive/MyDrive/2022-2024/NEU/IE 7300/Project/EMG_data_for_gestures-master'
!ls -lrt

In [231]:
# List out all the available files in the project's environment
files_path = set()
for dirname, _, filenames in os.walk('/content/drive/MyDrive/2022-2024/NEU/IE 7300/Project/EMG_data_for_gestures-master/'):
    for filename in filenames:
        f_path = os.path.join(dirname, filename)
        files_path.add(f_path)

In [232]:
df_time_series = pd.DataFrame()
for id, file in enumerate(tqdm(sorted(files_path))):
    print(file.split('/')[-2])
    sub = int(file.split('/')[-2])
    data = pd.read_csv(file, sep='\t')
    subject_id = np.ones([len(data),1], dtype=np.int16)*sub
    print('Subject Id: ', sub, ' Shape: ', subject_id.shape)
    # Add the subject into the data
    data['subject_id'] = subject_id
    df_time_series = pd.concat([df_time_series, data], axis=0, ignore_index=True, copy=True)
    # if id%2 == 1: 
    #     all_train = pd.concat([all_train, data], axis=0, ignore_index=True, copy=True)
    # else:
    #     all_test = pd.concat([all_test, data], axis=0, ignore_index=True, copy=True)

print('Total Records: ', df_time_series.shape)

  3%|▎         | 2/72 [00:00<00:04, 14.00it/s]

01
Subject Id:  1  Shape:  (63196, 1)
01
Subject Id:  1  Shape:  (57974, 1)
02


  6%|▌         | 4/72 [00:00<00:05, 12.07it/s]

Subject Id:  2  Shape:  (72322, 1)
02
Subject Id:  2  Shape:  (64104, 1)
03
Subject Id:  3  Shape:  (56568, 1)
03


 11%|█         | 8/72 [00:00<00:05, 11.90it/s]

Subject Id:  3  Shape:  (49217, 1)
04
Subject Id:  4  Shape:  (59107, 1)
04
Subject Id:  4  Shape:  (55091, 1)
05


 14%|█▍        | 10/72 [00:00<00:05, 12.32it/s]

Subject Id:  5  Shape:  (57118, 1)
05
Subject Id:  5  Shape:  (50130, 1)
06
Subject Id:  6  Shape:  (51078, 1)
06


 17%|█▋        | 12/72 [00:00<00:04, 12.23it/s]

Subject Id:  6  Shape:  (48541, 1)
07
Subject Id:  7  Shape:  (68697, 1)
07


 19%|█▉        | 14/72 [00:01<00:05, 11.15it/s]

Subject Id:  7  Shape:  (63943, 1)
08
Subject Id:  8  Shape:  (60280, 1)
08


 22%|██▏       | 16/72 [00:01<00:05, 10.53it/s]

Subject Id:  8  Shape:  (57668, 1)
09
Subject Id:  9  Shape:  (62770, 1)
09


 25%|██▌       | 18/72 [00:01<00:05, 10.08it/s]

Subject Id:  9  Shape:  (64877, 1)
10
Subject Id:  10  Shape:  (61641, 1)
10


 29%|██▉       | 21/72 [00:01<00:05,  9.30it/s]

Subject Id:  10  Shape:  (61448, 1)
11
Subject Id:  11  Shape:  (74681, 1)
11


 32%|███▏      | 23/72 [00:02<00:05,  8.44it/s]

Subject Id:  11  Shape:  (72645, 1)
12
Subject Id:  12  Shape:  (65920, 1)
12


 33%|███▎      | 24/72 [00:02<00:09,  4.80it/s]

Subject Id:  12  Shape:  (62631, 1)
13


 35%|███▍      | 25/72 [00:03<00:11,  4.02it/s]

Subject Id:  13  Shape:  (75676, 1)
13


 38%|███▊      | 27/72 [00:03<00:09,  4.97it/s]

Subject Id:  13  Shape:  (77564, 1)
14
Subject Id:  14  Shape:  (52821, 1)
14


 40%|████      | 29/72 [00:03<00:06,  6.41it/s]

Subject Id:  14  Shape:  (48182, 1)
15
Subject Id:  15  Shape:  (53553, 1)
15


 43%|████▎     | 31/72 [00:03<00:05,  7.29it/s]

Subject Id:  15  Shape:  (51843, 1)
16
Subject Id:  16  Shape:  (55489, 1)
16


 46%|████▌     | 33/72 [00:04<00:05,  7.43it/s]

Subject Id:  16  Shape:  (50012, 1)
17
Subject Id:  17  Shape:  (65227, 1)
17


 47%|████▋     | 34/72 [00:04<00:05,  6.94it/s]

Subject Id:  17  Shape:  (66858, 1)
18
Subject Id:  18  Shape:  (62354, 1)


 50%|█████     | 36/72 [00:04<00:05,  6.83it/s]

18
Subject Id:  18  Shape:  (66958, 1)
19


 53%|█████▎    | 38/72 [00:04<00:04,  7.11it/s]

Subject Id:  19  Shape:  (58818, 1)
19
Subject Id:  19  Shape:  (51088, 1)
20


 56%|█████▌    | 40/72 [00:05<00:04,  7.20it/s]

Subject Id:  20  Shape:  (65349, 1)
20
Subject Id:  20  Shape:  (62504, 1)
21

 57%|█████▋    | 41/72 [00:05<00:04,  7.14it/s]


Subject Id:  21  Shape:  (62365, 1)
21


 58%|█████▊    | 42/72 [00:05<00:04,  6.75it/s]

Subject Id:  21  Shape:  (56882, 1)
22
Subject Id:  22  Shape:  (61788, 1)


 61%|██████    | 44/72 [00:05<00:04,  6.66it/s]

22
Subject Id:  22  Shape:  (57841, 1)
23


 62%|██████▎   | 45/72 [00:05<00:04,  6.05it/s]

Subject Id:  23  Shape:  (60135, 1)
23
Subject Id:  23

 64%|██████▍   | 46/72 [00:06<00:04,  5.55it/s]

  Shape:  (55484, 1)
24


 65%|██████▌   | 47/72 [00:06<00:04,  5.11it/s]

Subject Id:  24  Shape:  (61968, 1)
24


 67%|██████▋   | 48/72 [00:06<00:04,  5.05it/s]

Subject Id:  24  Shape:  (54972, 1)
25


 68%|██████▊   | 49/72 [00:06<00:04,  4.73it/s]

Subject Id:  25  Shape:  (62681, 1)
25


 69%|██████▉   | 50/72 [00:07<00:04,  4.70it/s]

Subject Id:  25  Shape:  (54066, 1)
26


 71%|███████   | 51/72 [00:07<00:04,  4.64it/s]

Subject Id:  26  Shape:  (56151, 1)
26
Subject Id:  26  Shape:  (50003, 1)


 74%|███████▎  | 53/72 [00:07<00:04,  4.72it/s]

27
Subject Id:  27  Shape:  (56688, 1)
27
Subject Id:  27  Shape:  (50111, 1)


 76%|███████▋  | 55/72 [00:08<00:03,  4.68it/s]

28
Subject Id:  28  Shape:  (50513, 1)
28
Subject Id:  28  Shape:  (47253, 1)


 78%|███████▊  | 56/72 [00:08<00:03,  4.69it/s]

29
Subject Id:  29  Shape:  (53904, 1)


 79%|███████▉  | 57/72 [00:08<00:03,  4.65it/s]

29
Subject Id:  29  Shape:  (52083, 1)


 81%|████████  | 58/72 [00:08<00:02,  4.71it/s]

30
Subject Id:  30  Shape:  (77878, 1)


 82%|████████▏ | 59/72 [00:09<00:02,  4.42it/s]

30
Subject Id:  30  Shape:  (70683, 1)


 85%|████████▍ | 61/72 [00:09<00:02,  4.49it/s]

31
Subject Id:  31  Shape:  (44927, 1)
31
Subject Id:  31  Shape:  (46096, 1)


 88%|████████▊ | 63/72 [00:09<00:01,  4.63it/s]

32
Subject Id:  32  Shape:  (62719, 1)
32


 89%|████████▉ | 64/72 [00:10<00:01,  4.85it/s]

Subject Id:  32  Shape:  (60211, 1)
33
Subject Id:  33  Shape:  (59017, 1)


 90%|█████████ | 65/72 [00:10<00:01,  4.93it/s]

33
Subject Id:  33  Shape:  (53088, 1)


 92%|█████████▏| 66/72 [00:10<00:01,  4.65it/s]

34


 93%|█████████▎| 67/72 [00:11<00:01,  3.14it/s]

Subject Id:  34  Shape:  (79765, 1)
34
Subject Id:  34  Shape:  (51438, 1)


 96%|█████████▌| 69/72 [00:11<00:00,  3.94it/s]

35
Subject Id:  35  Shape:  (50417, 1)
35
Subject Id:  35  Shape:  (49084, 1)


 97%|█████████▋| 70/72 [00:11<00:00,  3.07it/s]

36
Subject Id:  36  Shape:  (52390, 1)


 99%|█████████▊| 71/72 [00:12<00:00,  3.30it/s]

36
Subject Id:  36  Shape:  (49364, 1)


100%|██████████| 72/72 [00:12<00:00,  5.80it/s]

Total Records:  (4237908, 11)


In [233]:
df_time_series.shape

(4237908, 11)

In [234]:
df_time_series['class'].unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7., nan])

In [ ]:
df = df_time_series
df = df.drop(df[['class']==0 or df['class']==7].index)

In [239]:
df_time_series=df_time_series.drop(columns=["time"])
Class = df_time_series["class"]
print(Class.unique())
print("Value Count :\n", df_time_series["class"].value_counts())

[ 1.  2.  3.  4.  5.  6. nan]
Value Count :
 6.0    253009
5.0    251733
4.0    251570
1.0    250055
3.0    249494
2.0    243193
Name: class, dtype: int64


In [236]:
##drop gesture 0 and 7 
index_numbers_1=df_time_series[df_time_series["class"]==0].index 
df_time_series.drop(index_numbers_1,inplace=True)
index_numbers_2=df_time_series[df_time_series["class"]==7].index
df_time_series.drop(index_numbers_2,inplace=True)

In [237]:
df_time_series.shape

(1499055, 11)

In [218]:
!pip install nolds
!pip install pycatch22
!pip install torchsummary
# !pip install pyeeg


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [230]:
df_time_series['class'].unique()

array([1.])

In [220]:
import statistics
from scipy import stats
from scipy.fft import rfft, rfftfreq
from scipy.signal import butter, filtfilt
import scipy
import pycatch22
import tensorflow as tf
from tensorflow import keras
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from torchsummary import summary

In [221]:
import warnings
import os
from tqdm import tqdm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pywt
import librosa
import nolds
# import pyeeg
warnings.filterwarnings('ignore')
sns.set_style('darkgrid')
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_colwidth', 500)

In [222]:
for subject_id in df_time_series['subject_id'].unique():
    for channel in range(1,2):
        if subject_id == 1:
            sub_df = df_time_series.loc[df_time_series['subject_id']==subject_id, f'channel{channel}']
            intervals = np.array_split(sub_df, len(sub_df)//500)
interval = intervals[0]            
peaks = scipy.signal.find_peaks(interval)
peaks = np.array(peaks)
print(peaks[0][1])
interval = interval.reset_index()
interval.iloc[63]

63


index       2350.00000
channel1      -0.00001
Name: 63, dtype: float64

In [223]:
for subject_id in df_time_series['subject_id'].unique():
    for channel in range(1,2):
        if subject_id == 1:
            df_time_series = df_time_series.loc[df_time_series['class']==1] 
            sub_df = df_time_series.loc[df_time_series['subject_id']==subject_id, f'channel{channel}']
print(sub_df)

2287    -0.00001
2288    -0.00001
2289    -0.00001
2290    -0.00001
2291    -0.00001
          ...   
94903   -0.00001
94904   -0.00001
94905   -0.00001
94906   -0.00001
94907    0.00001
Name: channel1, Length: 7311, dtype: float64


In [238]:
df_time_series['class'].nunique()

6

In [246]:
print(df_time_series[df_time_series['class'] == np.nan])

Empty DataFrame
Columns: [channel1, channel2, channel3, channel4, channel5, channel6, channel7, channel8, class, subject_id]
Index: []


In [247]:
df_time_series

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
2287     -0.00001   0.00000  -0.00001   0.00000   0.00000  -0.00001  -0.00001   
2288     -0.00001  -0.00002   0.00000  -0.00001  -0.00001  -0.00001  -0.00003   
2289     -0.00001  -0.00002   0.00000  -0.00001  -0.00001  -0.00001  -0.00003   
2290     -0.00001  -0.00002   0.00000  -0.00001  -0.00001  -0.00001  -0.00003   
2291     -0.00001  -0.00002   0.00000  -0.00001  -0.00001  -0.00001  -0.00003   
...           ...       ...       ...       ...       ...       ...       ...   
4237208   0.00009   0.00001   0.00003   0.00001  -0.00003  -0.00008   0.00004   
4237209   0.00009   0.00001   0.00003   0.00001  -0.00003  -0.00008   0.00004   
4237210   0.00009   0.00001   0.00003   0.00001  -0.00003  -0.00008   0.00004   
4237211   0.00014   0.00003  -0.00001   0.00001  -0.00012   0.00006  -0.00007   
4237212   0.00014   0.00003  -0.00001   0.00001  -0.00012   0.00006  -0.00007   

         channel8  class  subject_id  
2287      0.00001    1.0           1  
2288     -0.00002    1.0           1  
2289     -0.00002    1.0           1  
2290     -0.00002    1.0           1  
2291     -0.00002    1.0           1  
...           ...    ...         ...  
4237208   0.00000    6.0          36  
4237209   0.00000    6.0          36  
4237210   0.00000    6.0          36  
4237211  -0.00013    6.0          36  
4237212  -0.00013    6.0          36  

[1499055 rows x 10 columns]

In [273]:
for subject_id in range(1,2):
     for channel in range(1, 2):
        sub_df = df_time_series.loc[df_time_series['subject_id']==subject_id, f'channel{channel}']
        intervals = np.array_split(sub_df, len(sub_df)//600)
        peaks, properties = scipy.signal.find_peaks(intervals[0])
        interval = intervals[0]
        print(interval)

2287   -0.00001
2288   -0.00001
2289   -0.00001
2290   -0.00001
2291   -0.00001
         ...   
2889    0.00000
2890    0.00000
2891    0.00000
2892    0.00000
2893    0.00000
Name: channel1, Length: 607, dtype: float64


In [269]:
print(peaks)
interval = intervals[0]
interval = interval.reset_index(drop=True)
peak = [interval[ind] for ind in peaks]
print(peak)

[ 46  63  97 132 171 238 273 308 337 366 388 424 448 472 508 575]
[0.0, -1e-05, 0.0, 1e-05, 0.0, 1e-05, 0.0, 1e-05, 1e-05, 0.0, -1e-05, 0.0, 0.0, -1e-05, -1e-05, 1e-05]


In [265]:
interval

-1e-05

In [271]:
def catch22_features(df, signal_interval=600):
    catch22_list = []
    # iterate over each subject in the data
    for subject_id in df['subject_id'].unique():
        # iterate over each channel in the data
        for channel in range(1, 9):
            #for target in df['class'].unique():
                #print(target," ")       
                #df1 = df.loc[df['class']==target]
                sub_df = df.loc[df['subject_id']==subject_id, f'channel{channel}']
                # split the data into intervals of length 1024
                intervals = np.array_split(sub_df, len(sub_df)//signal_interval)
                y_segments = np.array_split(df.loc[df['subject_id']==subject_id, 'class'], len(sub_df)//signal_interval)
                # for each signal interval
                for int_idx, interval in enumerate(intervals):
                    # apply catch22 on the interval and compute the mean of all the features
                    features_interval = pycatch22.catch22_all(interval)
                    # compute more statistical features for the data of each channel
                    interval_stats = {}
                    class_mode = statistics.mode(y_segments[int_idx])
                    interval_stats['class_mode'] = class_mode
                    interval_stats['subject_id'] = subject_id
                    interval_stats['channel'] = channel
                    interval_stats['interval'] = int_idx
                    #interval_stats['mean'] = np.mean(interval)
                    #interval_stats['std'] = np.std(interval)
                    #interval_stats['var'] = np.var(interval)
                    interval_stats['min'] = np.min(interval)
                    interval_stats['max'] = np.min(interval)
                    #interval_stats['ptp'] = np.ptp(interval)    
                    interval_stats['rms'] = np.sqrt(np.mean(interval**2))    
                    peaks = scipy.signal.find_peaks(interval)
                    interval_stats['freq1'] = interval.iloc[peaks[0][1]] * 1000
                    interval_stats['freq2'] = interval.iloc[peaks[0][2]] * 1000
                    interval_stats['freq3'] = interval.iloc[peaks[0][3]] * 1000
                    #interval_stats['skew'] = stats.skew(interval)    
                    #interval_stats['kurtosis'] = stats.kurtosis(interval)    
                    #map feature names to feature values for each signal interval
                    features_mean = {feature_name: feature_value for feature_name, feature_value in zip(features_interval['names'], features_interval['values'])}
                    interval_dict = {**interval_stats, **features_mean}
                    catch22_list.append(interval_stats)

    catch22_df = pd.DataFrame(catch22_list)
    return catch22_df

In [272]:
catch22_data = catch22_features(df_time_series)

In [274]:
catch22_data

class_mode  subject_id  channel  interval      min      max       rms  \
0             1.0           1        1         0 -0.00003 -0.00003  0.000015   
1             1.0           1        1         1 -0.00004 -0.00004  0.000016   
2             1.0           1        1         2 -0.00004 -0.00004  0.000014   
3             2.0           1        1         3 -0.00111 -0.00111  0.000228   
4             2.0           1        1         4 -0.00063 -0.00063  0.000225   
...           ...         ...      ...       ...      ...      ...       ...   
19827         5.0          36        8        55 -0.00009 -0.00009  0.000034   
19828         5.0          36        8        56 -0.00008 -0.00008  0.000029   
19829         6.0          36        8        57 -0.00019 -0.00019  0.000059   
19830         6.0          36        8        58 -0.00030 -0.00030  0.000093   
19831         6.0          36        8        59 -0.00031 -0.00031  0.000086   

       freq1  freq2  freq3  
0      -0.01   0.00   0.01  
1       0.00   0.02   0.01  
2       0.00   0.00   0.02  
3       0.02   0.00   0.00  
4       0.18   0.24   0.01  
...      ...    ...    ...  
19827   0.02   0.01   0.02  
19828   0.02   0.03   0.01  
19829   0.01   0.03   0.02  
19830   0.07   0.14   0.02  
19831   0.07   0.10   0.05  

[19832 rows x 10 columns]

In [275]:
##pivoting channle to columns
pivoted_catch22 = catch22_data.pivot(index = ['class_mode','subject_id','interval'],columns='channel')

In [276]:
pivoted_catch22 = pivoted_catch22.reset_index()

In [277]:
pivoted_catch22

class_mode subject_id interval      min                             \
channel                                       1        2        3        4   
0              1.0          1        0 -0.00003 -0.00007 -0.00007 -0.00005   
1              1.0          1        1 -0.00004 -0.00006 -0.00008 -0.00007   
2              1.0          1        2 -0.00004 -0.00007 -0.00008 -0.00005   
3              1.0          1       19 -0.00004 -0.00008 -0.00009 -0.00006   
4              1.0          1       20 -0.00003 -0.00010 -0.00009 -0.00007   
...            ...        ...      ...      ...      ...      ...      ...   
2474           6.0         36       44 -0.00032 -0.00017 -0.00009 -0.00009   
2475           6.0         36       45 -0.00035 -0.00014 -0.00006 -0.00008   
2476           6.0         36       57 -0.00024 -0.00021 -0.00012 -0.00020   
2477           6.0         36       58 -0.00016 -0.00007 -0.00006 -0.00011   
2478           6.0         36       59 -0.00042 -0.00008 -0.00006 -0.00014   

                                                 max                    \
channel        5        6        7        8        1        2        3   
0       -0.00004 -0.00003 -0.00003 -0.00003 -0.00003 -0.00007 -0.00007   
1       -0.00004 -0.00004 -0.00003 -0.00004 -0.00004 -0.00006 -0.00008   
2       -0.00003 -0.00004 -0.00003 -0.00004 -0.00004 -0.00007 -0.00008   
3       -0.00004 -0.00006 -0.00003 -0.00003 -0.00004 -0.00008 -0.00009   
4       -0.00004 -0.00004 -0.00004 -0.00005 -0.00003 -0.00010 -0.00009   
...          ...      ...      ...      ...      ...      ...      ...   
2474    -0.00030 -0.00022 -0.00032 -0.00032 -0.00032 -0.00017 -0.00009   
2475    -0.00018 -0.00015 -0.00018 -0.00033 -0.00035 -0.00014 -0.00006   
2476    -0.00035 -0.00054 -0.00014 -0.00019 -0.00024 -0.00021 -0.00012   
2477    -0.00027 -0.00027 -0.00021 -0.00030 -0.00016 -0.00007 -0.00006   
2478    -0.00028 -0.00055 -0.00023 -0.00031 -0.00042 -0.00008 -0.00006   

                                                           rms            \
channel        4        5        6        7        8         1         2   
0       -0.00005 -0.00004 -0.00003 -0.00003 -0.00003  0.000015  0.000025   
1       -0.00007 -0.00004 -0.00004 -0.00003 -0.00004  0.000016  0.000023   
2       -0.00005 -0.00003 -0.00004 -0.00003 -0.00004  0.000014  0.000024   
3       -0.00006 -0.00004 -0.00006 -0.00003 -0.00003  0.000017  0.000031   
4       -0.00007 -0.00004 -0.00004 -0.00004 -0.00005  0.000015  0.000032   
...          ...      ...      ...      ...      ...       ...       ...   
2474    -0.00009 -0.00030 -0.00022 -0.00032 -0.00032  0.000116  0.000071   
2475    -0.00008 -0.00018 -0.00015 -0.00018 -0.00033  0.000068  0.000038   
2476    -0.00020 -0.00035 -0.00054 -0.00014 -0.00019  0.000066  0.000074   
2477    -0.00011 -0.00027 -0.00027 -0.00021 -0.00030  0.000047  0.000029   
2478    -0.00014 -0.00028 -0.00055 -0.00023 -0.00031  0.000116  0.000027   

                                                                    freq1  \
channel         3         4         5         6         7         8     1   
0        0.000031  0.000019  0.000015  0.000013  0.000014  0.000014 -0.01   
1        0.000024  0.000023  0.000017  0.000014  0.000013  0.000015  0.00   
2        0.000029  0.000019  0.000015  0.000015  0.000014  0.000014  0.00   
3        0.000042  0.000022  0.000015  0.000020  0.000015  0.000014 -0.01   
4        0.000052  0.000023  0.000014  0.000015  0.000016  0.000017 -0.01   
...           ...       ...       ...       ...       ...       ...   ...   
2474     0.000037  0.000041  0.000129  0.000096  0.000118  0.000117 -0.05   
2475     0.000027  0.000033  0.000101  0.000074  0.000066  0.000070  0.03   
2476     0.000037  0.000081  0.000169  0.000141  0.000054  0.000059 -0.01   
2477     0.000026  0.000050  0.000116  0.000161  0.000082  0.000093  0.01   
2478     0.000028  0.000042  0.000161  0.000161  0.000085  0.000086  0.02   

                                       

In [278]:
m = {t: '_'.join(str(t)) for t in pivoted_catch22.columns}
final_catch22 = pivoted_catch22.groupby(m, axis=1).mean()

In [279]:
final_catch22

(_'_c_l_a_s_s___m_o_d_e_'_,_ _'_'_)  (_'_f_r_e_q_1_'_,_ _1_)  \
0                                     1.0                    -0.01   
1                                     1.0                     0.00   
2                                     1.0                     0.00   
3                                     1.0                    -0.01   
4                                     1.0                    -0.01   
...                                   ...                      ...   
2474                                  6.0                    -0.05   
2475                                  6.0                     0.03   
2476                                  6.0                    -0.01   
2477                                  6.0                     0.01   
2478                                  6.0                     0.02   

      (_'_f_r_e_q_1_'_,_ _2_)  (_'_f_r_e_q_1_'_,_ _3_)  \
0                       -0.01                     0.04   
1                        0.01                     0.00   
2                       -0.01                     0.00   
3                       -0.02                     0.01   
4                        0.02                     0.03   
...                       ...                      ...   
2474                     0.04                     0.01   
2475                     0.02                     0.03   
2476                     0.19                     0.04   
2477                     0.01                     0.01   
2478                     0.01                    -0.01   

      (_'_f_r_e_q_1_'_,_ _4_)  (_'_f_r_e_q_1_'_,_ _5_)  \
0                        0.00                     0.01   
1                        0.02                     0.00   
2                        0.01                     0.00   
3                       -0.01                     0.00   
4                        0.01                     0.00   
...                       ...                      ...   
2474                     0.04                     0.02   
2475                     0.02                     0.01   
2476                     0.02                     0.23   
2477                     0.03                     0.09   
2478                    -0.01                     0.25   

      (_'_f_r_e_q_1_'_,_ _6_)  (_'_f_r_e_q_1_'_,_ _7_)  \
0                        0.00                    -0.01   
1                        0.00                     0.00   
2                        0.01                     0.00   
3                        0.00                     0.00   
4                       -0.01                     0.01   
...                       ...                      ...   
2474                     0.09                     0.10   
2475                     0.08                     0.14   
2476                     0.04                    -0.02   
2477                     0.01                     0.03   
2478                     0.17                     0.02   

      (_'_f_r_e_q_1_'_,_ _8_)  (_'_f_r_e_q_2_'_,_ _1_)  \
0                        0.00                     0.00   
1                        0.00                     0.02   
2                        0.00                     0.00   
3                        0.00                     0.00   
4                       -0.01                     0.01   
...                       ...                      ...   
2474                     0.33                     0.27   
2475                    -0.05                     0.04   
2476                     0.01                     0.21   
2477                     0.07                    -0.01   
2478                     0.07                    -0.01   

      (_'_f_r_e_q_2_'_,_ _2_)  (_'_f_r_e_q_2_'_,_ _3_)  \
0                       -0.01                    -0.03   
1                        0.00                     0.03   
2                        0.01                    -0.02   
3                        0.02                     0.02   
4                        0.00                     0.03   
...                       ...

In [281]:
final_catch22.columns = ['class','freq1_1','freq1_2','freq1_3','freq1_4','freq1_5','freq1_6','freq1_7','freq1_8',
                         'freq2_1','freq2_2','freq2_3','freq2_4','freq2_5','freq2_6','freq2_7','freq2_8',
                         'freq3_1','freq3_2','freq3_3','freq3_4','freq3_5','freq3_6','freq3_7','freq3_8','interval',
                         'max_1','max_2','max_3','max_4','max_5','max_6','max_7','max_8',
                         'min_1','min_2','min_3','min_4','min_5','min_6','min_7','min_8',
                         'rms_1','rms_2','rms_3','rms_4','rms_5','rms_6','rms_7','rms_8','subject_id']
print(final_catch22.head())

   class  freq1_1  freq1_2  freq1_3  freq1_4  freq1_5  freq1_6  freq1_7  \
0    1.0    -0.01    -0.01     0.04     0.00     0.01     0.00    -0.01   
1    1.0     0.00     0.01     0.00     0.02     0.00     0.00     0.00   
2    1.0     0.00    -0.01     0.00     0.01     0.00     0.01     0.00   
3    1.0    -0.01    -0.02     0.01    -0.01     0.00     0.00     0.00   
4    1.0    -0.01     0.02     0.03     0.01     0.00    -0.01     0.01   

   freq1_8  freq2_1  freq2_2  freq2_3  freq2_4  freq2_5  freq2_6  freq2_7  \
0     0.00     0.00    -0.01    -0.03     0.00     0.01     0.02     0.00   
1     0.00     0.02     0.00     0.03     0.02     0.00     0.00     0.00   
2     0.00     0.00     0.01    -0.02     0.02     0.00    -0.01     0.00   
3     0.00     0.00     0.02     0.02     0.02    -0.01     0.00     0.01   
4    -0.01     0.01     0.00     0.03     0.02     0.01     0.00     0.01   

   freq2_8  freq3_1  freq3_2  freq3_3  freq3_4  freq3_5  freq3_6  freq3_7  \
0     0.0

In [285]:
final_catch22.tail(5)

class  freq1_1  freq1_2  freq1_3  freq1_4  freq1_5  freq1_6  freq1_7  \
2474    6.0    -0.05     0.04     0.01     0.04     0.02     0.09     0.10   
2475    6.0     0.03     0.02     0.03     0.02     0.01     0.08     0.14   
2476    6.0    -0.01     0.19     0.04     0.02     0.23     0.04    -0.02   
2477    6.0     0.01     0.01     0.01     0.03     0.09     0.01     0.03   
2478    6.0     0.02     0.01    -0.01    -0.01     0.25     0.17     0.02   

      freq1_8  freq2_1  freq2_2  freq2_3  freq2_4  freq2_5  freq2_6  freq2_7  \
2474     0.33     0.27     0.04     0.03     0.01     0.31     0.15     0.16   
2475    -0.05     0.04     0.03     0.06     0.00    -0.02     0.11     0.15   
2476     0.01     0.21     0.10     0.10     0.00     0.19     0.01    -0.01   
2477     0.07    -0.01     0.01     0.03     0.04     0.07     0.12     0.08   
2478     0.07    -0.01     0.00     0.00     0.04     0.09    -0.05     0.00   

      freq2_8  freq3_1  freq3_2  freq3_3  freq3_4  freq3_5  freq3_6  freq3_7  \
2474     0.10     0.10     0.02     0.01     0.00     0.08     0.00    -0.07   
2475     0.03     0.05     0.29     0.04     0.05     0.02     0.05     0.05   
2476     0.03     0.10     0.01     0.09     0.11     0.00     0.03     0.00   
2477     0.14     0.01    -0.01    -0.01     0.01     0.13     0.09     0.06   
2478     0.10     0.03     0.03     0.01     0.04     0.09    -0.01     0.07   

      freq3_8  interval    max_1    max_2    max_3    max_4    max_5    max_6  \
2474     0.13      44.0 -0.00032 -0.00017 -0.00009 -0.00009 -0.00030 -0.00022   
2475     0.04      45.0 -0.00035 -0.00014 -0.00006 -0.00008 -0.00018 -0.00015   
2476     0.02      57.0 -0.00024 -0.00021 -0.00012 -0.00020 -0.00035 -0.00054   
2477     0.02      58.0 -0.00016 -0.00007 -0.00006 -0.00011 -0.00027 -0.00027   
2478     0.05      59.0 -0.00042 -0.00008 -0.00006 -0.00014 -0.00028 -0.00055   

        max_7    max_8    min_1    min_2    min_3    min_4    min_5    min_6  \
2474 -0.00032 -0.00032 -0.00032 -0.00017 -0.00009 -0.00009 -0.00030 -0.00022   
2475 -0.00018 -0.00033 -0.00035 -0.00014 -0.00006 -0.00008 -0.00018 -0.00015   
2476 -0.00014 -0.00019 -0.00024 -0.00021 -0.00012 -0.00020 -0.00035 -0.00054   
2477 -0.00021 -0.00030 -0.00016 -0.00007 -0.00006 -0.00011 -0.00027 -0.00027   
2478 -0.00023 -0.00031 -0.00042 -0.00008 -0.00006 -0.00014 -0.00028 -0.00055   

        min_7    min_8     rms_1     rms_2     rms_3     rms_4     rms_5  \
2474 -0.00032 -0.00032  0.000116  0.000071  0.000037  0.000041  0.000129   
2475 -0.00018 -0.00033  0.000068  0.000038  0.000027  0.000033  0.000101   
2476 -0.00014 -0.00019  0.000066  0.000074  0.000037  0.000081  0.000169   
2477 -0.00021 -0.00030  0.000047  0.000029  0.000026  0.000050  0.000116   
2478 -0.00023 -0.00031  0.000116  0.000027  0.000028  0.000042  0.000161   

         rms_6     rms_7     rms_8  subject_id  
2474  0.000096  0.000118  0.000117        36.0  
2475  0.000074  0.000066  0.000070        36.0  
2476  0.000141  0.000054  0.000059        36.0  
2477  0.000161  0.000082  0.000093        36.0  
2478  0.000161  0.000085  0.000086        36.0

In [282]:
final_catch22.shape

(2479, 51)

In [283]:
## Training SVM Classifier
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
estimators=[]
accuracy=[]
f1_macro=[]
svc=SVC(C=100,kernel='poly',gamma=0.01,decision_function_shape='ovo')
features=final_catch22.drop(columns=["subject_id","class","interval"])
labels=final_catch22["class"]
##Training and testing set splitting
X_train, X_test,y_train,y_test= train_test_split(features,labels,test_size=0.30, random_state=1, shuffle=False)
## Data normalization
mean = X_train.mean(axis=0)
std = X_train.std(axis=0)
X_train -= mean
X_train /= std
X_test -= mean
X_test /= std
svc.fit(X_train,y_train)
y_test_pred=svc.predict(X_test)
y=f1_score(y_test,y_test_pred,average='macro') 
x=confusion_matrix(y_test,y_test_pred)
a=accuracy_score(y_test,y_test_pred)
print("F1 Score: ", y)
print("Confusion Matrix: \n")
print(x)
print("Accuracy: ", a)
#estimators.append(print_estimator_name(svc))
f1_macro.append(y)
accuracy.append(a)
plt.show()

F1 Score:  0.05128205128205129
Confusion Matrix: 

[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  5  46  60 159  60   0]
 [ 93  63 193  65   0   0]]
Accuracy:  0.08064516129032258
